spring:
  datasource:
    url: jdbc:mysql://mysql.jmall.com:3306/jmall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
      address: redis.jmall.com:6379
      timeout: 3000
      database: 0
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000
        min-idle: 4
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos.jmall.com:8848
        group: JMALL

dubbo:
  protocol:
    name: dubbo
    port: 20883
  scan:
    base-packages: com.jmall.pay.services
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: jmall-shopping-services-provider,jmall-user-services-provider,jmall-order-services-provider
logging:
  config:
    classpath: logback.xml
