spring:
  profiles:
    active: dev
  application:
    name: jmall-comment-services-provider
mybatis:
  mapper-locations: classpath*:com/jmall/comment/dal/persistence/*Mapper.xml"
  type-aliases-package: com.jmall.comment.dal.entitys
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

