spring:
  datasource:
    url: jdbc:mysql://mysql.jmall.com:3306/jmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
    address: localhost:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: localhost:8848
        metadata: localhost:8848
  ##以下下配置是springboot autoconfig 认初始化时会加载的参数，但是user可以重现构建一下参数
  ##自定义构造的bean可查看kafkaConfig
  kafka:
    bootstrapServers: 192.168.126.128:9092,192.168.126.129:9092,192.168.126.130:9092
    consumer:
      auto-offset-reset: latest
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.jmall.user.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

dubbo:
  protocol:
    name: dubbo
    port: 20887
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services:
  scan:
    base-packages: com.jmall.user.services
lock:
  zookeeper:
    zkHosts: zookeeper://192.168.126.129:2181?backup=192.168.126.128:2181,192.168.126.130:2181
    sessionTimeout: 30000
    connectionTimeout: 30000
    ## 共享一个zk链接
    singleton: true
    ## 全局path前缀,常用来区分不同的应用
    namespace: zkLock
email:
  mail-server-host: smtp.163.com
  mail-server-port: 25
  from-address:
  to-addresss:
  cc-addresss:
  username:
  password:
  mailSmtpAuth: true
  subject: 通知
  content: 你好，纪红，到办公室来,请不要上班时间看电视剧.
  template-path: emailTemplate