spring:
  datasource:
    url: jdbc:mysql://mysql.jmall.com:3306/jmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
    address: redis.jmall.com:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
#        enabled: true
#        register-enabled: true
        server-addr: nacos.jmall.com:8848
        group: JMALL
  ##以下下配置是springboot autoconfig 认初始化时会加载的参数，但是user可以重现构建一下参数
  ##自定义构造的bean可查看kafkaConfig
  kafka:
    bootstrapServers: kafka1.jmall.com:9092,kafka2.jmall.com:9092,kafka3.jmall.com:9092
    consumer:
      auto-offset-reset: latest
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.jmall.user.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services:
  scan:
    base-packages: com.jmall.user.services
lock:
  zookeeper:
    zkHosts: zookeeper://zk3.jmall.com:2181?backup=zk2.jmall.com:2181,zk1.jmall.com:2181
    sessionTimeout: 30000
    connectionTimeout: 30000
    ## 共享一个zk链接
    singleton: true
    ## 全局path前缀,常用来区分不同的应用
    namespace: zkLock
email:
  mail-server-host: smtp.163.com
  mail-server-port: 25
  from-address: xxxx@163.com
  to-addresss:
  cc-addresss:
  username:
  password:
  mailSmtpAuth: true
  subject: 激活邮件，请点击激活
  content:
  template-path: emailTemplate
  userMailActiveUrl: http://localhost:9999/jmall-user/user/verify