dubbo:
  cloud:
    subscribed-services: jmall-user-services-provider
  scan:
    base-packages: com.jmall.user
captchaFlag : true

spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos.jmall.com:8848
        group: JMALL